import os
from pathlib import Path
from dataclasses import dataclass, field
import subprocess

from icecream import ic  # type: ignore
import pyudev  # type: ignore

from nixos_gen_config import auxiliary_functions  # type: ignore
from nixos_gen_config.arguments import process_args  # type: ignore
from nixos_gen_config.hardware import cpu_section, udevGet # type: ignore
from nixos_gen_config.classes import nixConfigAttrs


def main():
    nixConfig = nixConfigAttrs()
    uniq = auxiliary_functions.uniq
    to_nix_string_list = auxiliary_functions.to_nix_string_list
    to_nix_list = auxiliary_functions.to_nix_list
    to_nix_multi_line_list = auxiliary_functions.to_nix_multi_line_list
    to_nix_true_attr = auxiliary_functions.to_nix_true_attr
    to_nix_false_attr = auxiliary_functions.to_nix_false_attr

    args = process_args()

    out_dir = os.path.abspath(args.dir)
    if args.root:
        root_dir = os.path.normpath(args.root)
    else:
        root_dir = ""
    force = args.force
    no_filesystems = args.no_filesystems
    show_hardware_config = args.show_hardware_config

    if not args.debug:
        ic.disable()

    try:
        os.mkdir(out_dir)
    except FileExistsError:
        pass
    except OSError as error:
        print(f"Creation of {out_dir} failed {error}")


    def virt_section(nix_config: nixConfigAttrs) -> None:
        virtcmd = ""
        # systemd-detect-virt exits with 1 when virt = none
        try:
            virtcmd = subprocess.run(["systemd-detect-virt"], capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError:
            # Provide firmware for devices that are not detected by this script,
            # unless we're in a VM/container.
            nix_config.imports.append('(modulesPath + "/installer/scan/not-detected.nix")')


        if virtcmd:
            virt = (virtcmd.stdout).strip()
            if virt == "oracle":
                nix_config.attrs.append(to_nix_true_attr("virtualisation.virtualbox.guest.enable"))
            if virt == "microsoft":
                nix_config.attrs.append(to_nix_true_attr("virtualisation.hypervGuest.enable"))
            if virt == "systemd-nspawn":
                nix_config.attrs.append(to_nix_true_attr("boot.isContainer"))
            if virt in ("qemu", "kvm", "bochs"):
                nix_config.imports.append('(modulesPath + "/profiles/qemu-quest.nix")')


    udevGet(nixConfig)

    video_driver = 0
    if video_driver:
        nixConfig.attrs.append(f'services.xserver.videoDrivers = [ "{video_driver}" ]')

    def gen_hw_file(nix_config: nixConfigAttrs) -> None:
        # unpacking using * so we don't return, for example, "['usbhid']"
        initrd_available_kernel_modules = to_nix_string_list(*(uniq(nix_config.initrd_available_kernel_modules)))
        initrd_kernel_modules = to_nix_string_list(*(uniq(nix_config.initrd_kernel_modules)))
        kernel_modules = to_nix_string_list(*(uniq(nix_config.kernel_modules)))
        module_packages = to_nix_list(*(uniq(nix_config.module_packages)))
        firmware_packages = to_nix_list(*(uniq(nix_config.firmware_packages)))
        imports = to_nix_multi_line_list("    ", *nix_config.imports)
        # ic(initrdAvailableKernelModules)
        with open(f"{root_dir}{out_dir}/hardware-configuration.nix", "w", encoding='utf-8') as t_f:
            # ic(t_f)
            t_f.write(
                "# Do not modify this file!  It was generated by ‘nixos-generate-config’\n"
                "# and may be overwritten by future invocations.  Please make changes\n"
                "# to /etc/nixos/configuration.nix instead.\n"
                "{ config, lib, pkgs, modulesPath, ... }:\n"
                "\n"
                "{\n"
                f"  imports ={imports};\n"
                "\n"
                f"  boot.initrd.availableKernelModules = [{initrd_available_kernel_modules} ];\n"
                f"  boot.initrd.kernelModules = [{initrd_kernel_modules} ];\n"
                f"  boot.kernelModules = [{kernel_modules} ];\n"
                f"  boot.extraModulePackages = [{module_packages} ];\n"
                f"  hardware.firmware = [{firmware_packages} ];\n"
            )
            for attr in uniq(nixConfig.attrs):
                t_f.write("  " + attr + "\n")
            t_f.write("\n}\n")


    virt_section(nixConfig)

    cpu_section(nixConfig)

    gen_hw_file(nixConfig)


if __name__ == "__main__":
    main()
