import pyudev
from icecream import ic as ic
from nixos_gen_config.classes import NixConfigAttrs as NixConfigAttrs

def cpu_info(field: str) -> str: ...
def cpu_section(nix_config: NixConfigAttrs) -> None: ...
def gpu_section(nix_config: NixConfigAttrs) -> None: ...
def usb_keyboard(nix_config: NixConfigAttrs, device: pyudev.Device) -> None: ...
def pci(nix_config: NixConfigAttrs, device: pyudev.Device) -> None: ...
def wifi(nix_config: NixConfigAttrs, device: pyudev.Device) -> None: ...
def bcache(nix_config: NixConfigAttrs, device: pyudev.Device) -> None: ...
def udev_section(nix_config: NixConfigAttrs) -> None: ...
def virt_section(nix_config: NixConfigAttrs) -> None: ...
